## Environment for installing Mindboggle
##
## This environment is configured for circleci.com continuous integration
## (testing).
##
## Authors:
##    - Arno Klein, 2016  (arno@mindboggle.info)  http://binarybottle.com
##
## Copyright 2016,  Mindboggle team (mindboggle.info), Apache v2.0 License

#-----------------------------------------------------------------------------
# mindboggle-env environment:
#-----------------------------------------------------------------------------
name: mindboggle-env
#-----------------------------------------------------------------------------
# anaconda cloud channel for installing VTK 7.0.0:
#-----------------------------------------------------------------------------
channels:
    - clinicalgraphics
#-----------------------------------------------------------------------------
# mindboggle dependencies:
#-----------------------------------------------------------------------------
dependencies:
    - python=3.5.1
    - vtk=7.0.0
    #-------------------------------------------------------------------------
    # nipype:
    #-------------------------------------------------------------------------
    - scipy
    - networkx
    - lxml
    - simplejson
    - future
    - nose
    - pip
    - pip:
        - nibabel
        - prov
        - traits
        - xvfbwrapper
        - https://github.com/nipy/nipype/archive/master.zip
    #-------------------------------------------------------------------------
    # mindboggle's remaining dependencies:
    #-------------------------------------------------------------------------
    - cmake
    - matplotlib
    - numpy
    - pandas
    #-------------------------------------------------------------------------
    # additional testing tools:
    #-------------------------------------------------------------------------
    - ipython
    - pytest
    - coverage

